local keymap = vim.keymap.set
keymap({"n", "v"}, "<leader>a", "<cmd>lua require('vscode').action('cursor-harpoon.addEditor')<CR>")
keymap({"n", "v"}, "<leader>he", "<cmd>lua require('vscode').action('cursor-harpoon.editorQuickPick')<CR>")
-- keymap({"n", "v"}, "<C-e>", "<cmd>lua require('vscode').action('vscode-harpoon.editEditors')<CR>")
keymap({"n", "v"}, "<leader>1", "<cmd>lua require('vscode').action('cursor-harpoon.gotoEditor1')<CR>")
keymap({"n", "v"}, "<leader>2", "<cmd>lua require('vscode').action('cursor-harpoon.gotoEditor2')<CR>")
keymap({"n", "v"}, "<leader>3", "<cmd>lua require('vscode').action('cursor-harpoon.gotoEditor3')<CR>")
keymap({"n", "v"}, "<leader>4", "<cmd>lua require('vscode').action('cursor-harpoon.gotoEditor4')<CR>")
keymap({"n", "v"}, "<leader>5", "<cmd>lua require('vscode').action('cursor-harpoon.gotoEditor5')<CR>")
keymap({"n", "v"}, "<leader>6", "<cmd>lua require('vscode').action('cursor-harpoon.gotoEditor6')<CR>")
keymap({"n", "v"}, "<leader>7", "<cmd>lua require('vscode').action('cursor-harpoon.gotoEditor7')<CR>")
keymap({"n", "v"}, "<leader>8", "<cmd>lua require('vscode').action('cursor-harpoon.gotoEditor8')<CR>")
keymap({"n", "v"}, "<leader>9", "<cmd>lua require('vscode').action('cursor-harpoon.gotoEditor9')<CR>")
